### ISSUE TITLE
集群节点上运行程序时报错：cuda_runtime.h: No such file or directory...

### ISSUE THREAD

**Issue by MayCloud052** [blcuicall/BLCU-HPC#25]
**运行大模型微调脚本（基于deepspeed）：**
```
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`
MODEL="/home/syd83774/workspace/Qwen-VL-Chat-Int4" # Qwen/Qwen-VL-Chat-Int4 Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="/home/syd83774/workspace/test/test_Qwen-VL-Chat-Int4/toydataset.json"

export CUDA_VISIBLE_DEVICES=0

# Remember to use --fp16 instead of --bf16 due to autogptq
python finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --fp16 True \
    --fix_vit True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 2048 \
    --lazy_preprocess True \
    --gradient_checkpointing \
    --use_lora \
    --q_lora \
    --deepspeed finetune/ds_config_zero2.json
```
**报错信息：**
[2024-04-01 14:53:50,045] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama, use_cuda_fp16) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 5/5 [00:10<00:00,  2.01s/it]
Loading data...
Formatting inputs...Skip in lazy mode
/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Using /home/syd83774/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/syd83774/.cache/torch_extensions/py38_cu121/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /home/syd83774/.conda/envs/env_py38/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/csrc/adam -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include/TH -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include/THC -isystem /home/syd83774/.conda/envs/env_py38/include -isystem /home/syd83774/.conda/envs/env_py38/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 -std=c++17 -c /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/home/syd83774/.conda/envs/env_py38/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/csrc/adam -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include/TH -isystem /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/include/THC -isystem /home/syd83774/.conda/envs/env_py38/include -isystem /home/syd83774/.conda/envs/env_py38/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 -std=c++17 -c /home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
**cc1plus: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.**
Traceback (most recent call last):
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "finetune.py", line 367, in <module>
    train()
  File "finetune.py", line 360, in train
    trainer.train()
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/accelerate/accelerator.py", line 1255, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/accelerate/accelerator.py", line 1640, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 523, in jit_load
    op_module = load(name=self.name,
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1306, in load
    return _jit_compile(
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/syd83774/.conda/envs/env_py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'
**环境及相关依赖库版本：**
python：3.8
cuda：12.1
auto_gptq：0.7.1
deepspeed：0.14.0
ninja：1.11.1.1
peft：0.9.0
transformers：4.32.0
torch：2.2.1
**申请资源：**
salloc -G 1 -N 1

**Comment by chongruining** [comment]
参考https://github.com/microsoft/DeepSpeedExamples/issues/594
似乎是deepspeed与cuda版本不兼容的问题，我在节点上安装了ninja-build ，尝试重新运行，或切换不同的cuda版本并export到环境变量中

**Comment by Young-X** [comment]
我是用的ssh远程终端，nvidia-smi的cuda版本是11.0，安装的nvcc是11.6，环境配置都没问题，同样出现这个报错是什么原因？
